// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5mf52pddX4JykqxN3idS7N
// Component: jm-lBKIQa-
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_todo_mvc.module.css"; // plasmic-import: 5mf52pddX4JykqxN3idS7N/projectcss
import sty from "./PlasmicTestPage.module.css"; // plasmic-import: jm-lBKIQa-/css

import _68747470733A2F2F6968312E726564627562626C652E6E65742F696D6167652E313037363638373036362E303731362F73742C736D616C6C2C353037783530372D7061642C363030783630302C6638663866382E6A7067JpegWDrSaaJ2F from "./images/_68747470733A2F2F6968312E726564627562626C652E6E65742F696D6167652E313037363638373036362E303731362F73742C736D616C6C2C353037783530372D7061642C363030783630302C6638663866382E6A7067Jpeg.jpeg"; // plasmic-import: wDrSaaJ2f/picture

export type PlasmicTestPage__VariantMembers = {};

export type PlasmicTestPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestPage__VariantsArgs;
export const PlasmicTestPage__VariantProps = new Array<VariantPropType>();

export type PlasmicTestPage__ArgsType = {};
type ArgPropType = keyof PlasmicTestPage__ArgsType;
export const PlasmicTestPage__ArgProps = new Array<ArgPropType>();

export type PlasmicTestPage__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultTestPageProps {
  className?: string;
}

function PlasmicTestPage__RenderFunc(props: {
  variants: PlasmicTestPage__VariantsArgs;
  args: PlasmicTestPage__ArgsType;
  overrides: PlasmicTestPage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={"" as const}
            className={classNames(sty.img)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"750px" as const}
            loading={"lazy" as const}
            src={{
              src: _68747470733A2F2F6968312E726564627562626C652E6E65742F696D6167652E313037363638373036362E303731362F73742C736D616C6C2C353037783530372D7061642C363030783630302C6638663866382E6A7067JpegWDrSaaJ2F,
              fullWidth: 600,
              fullHeight: 600,
              aspectRatio: undefined
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestPage__VariantsArgs;
    args?: PlasmicTestPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTestPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTestPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestPage__ArgProps,
      internalVariantPropNames: PlasmicTestPage__VariantProps
    });

    return PlasmicTestPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestPage";
  } else {
    func.displayName = `PlasmicTestPage.${nodeName}`;
  }
  return func;
}

export const PlasmicTestPage = Object.assign(
  // Top-level PlasmicTestPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicTestPage
    internalVariantProps: PlasmicTestPage__VariantProps,
    internalArgProps: PlasmicTestPage__ArgProps
  }
);

export default PlasmicTestPage;
/* prettier-ignore-end */
